 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/storehouses", type: :request do
  
  # Storehouse. As you add validations to Storehouse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Storehouse.create! valid_attributes
      get storehouses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      storehouse = Storehouse.create! valid_attributes
      get storehouse_url(storehouse)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_storehouse_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      storehouse = Storehouse.create! valid_attributes
      get edit_storehouse_url(storehouse)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Storehouse" do
        expect {
          post storehouses_url, params: { storehouse: valid_attributes }
        }.to change(Storehouse, :count).by(1)
      end

      it "redirects to the created storehouse" do
        post storehouses_url, params: { storehouse: valid_attributes }
        expect(response).to redirect_to(storehouse_url(Storehouse.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Storehouse" do
        expect {
          post storehouses_url, params: { storehouse: invalid_attributes }
        }.to change(Storehouse, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post storehouses_url, params: { storehouse: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested storehouse" do
        storehouse = Storehouse.create! valid_attributes
        patch storehouse_url(storehouse), params: { storehouse: new_attributes }
        storehouse.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the storehouse" do
        storehouse = Storehouse.create! valid_attributes
        patch storehouse_url(storehouse), params: { storehouse: new_attributes }
        storehouse.reload
        expect(response).to redirect_to(storehouse_url(storehouse))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        storehouse = Storehouse.create! valid_attributes
        patch storehouse_url(storehouse), params: { storehouse: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested storehouse" do
      storehouse = Storehouse.create! valid_attributes
      expect {
        delete storehouse_url(storehouse)
      }.to change(Storehouse, :count).by(-1)
    end

    it "redirects to the storehouses list" do
      storehouse = Storehouse.create! valid_attributes
      delete storehouse_url(storehouse)
      expect(response).to redirect_to(storehouses_url)
    end
  end
end
